### ISSUE TITLE
Error including GoogleService-Info.plist

### ISSUE THREAD

**Issue by mcassola** [hansemannn/titanium-firebase-core#1]
I have the next error when i call the method FirebaseApp.configure() : "GoogleService-Info.plist could not find a valid GoogleService-Info.plist in your project"

I found similars issues: https://github.com/chrisribe/ti-firebase/issues/20
and apply it but i can't resolve the problem. Any idea?

$ appc ti build -p ios --build-only
Appcelerator Command-Line Interface, version 6.2.4
Copyright (c) 2014-2017, Appcelerator, Inc. All Rights Reserved.

Operating System
Name = Mac OS X
Version = 10.12.2
Architecture = 64bit

CPUs = 4

Memory = 8589934592

Node.js
Node.js Version = 4.6.0
npm Version = 2.15.9

Titanium CLI
CLI Version = 5.0.14

Titanium SDK
SDK Version = 6.2.2.GA
SDK Path = /Users/intermediaMac/Library/Application Support/Titanium/mobilesdk/osx/6.2.2.GA
Target Platform = iphone

[DEBUG] :  [object FirebaseCoreModule] loaded
[DEBUG] :  [object FirebaseCloudmessagingModule] loaded
[ERROR] :  Script Error {
[ERROR] :      column = 27;
[ERROR] :      line = 312;
[ERROR] :      message = "`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.";
[ERROR] :      sourceURL = "file:///Users/intermediaMac/Library/Developer/CoreSimulator/Devices/A5CEFBE1-54AB-4940-91EA-6AF467812CC4/data/Containers/Bundle/Application/05F8F50B-1D83-4AA0-B16D-784D4E29FEEB/QueryApp.app/alloy/controllers/home.js";
[ERROR] :  }

**Comment by hansemannn** [comment]
As mentioned in the related ticket, it needs to go into your resources, which is `Resources/` for classic projects and `app/assets/iphone` for Alloy.

**Comment by mitulbhalia** [comment]
Hi @mcassola 
Did you find any solution for this issue. I am getting same error with ti sdk 6.3.1 and 7.0.1 with version 1.1.0
