### ISSUE TITLE
GoogleService-Info.plist - Options is nil

### ISSUE THREAD

**Issue by michaelkaaring** [hansemannn/titanium-firebase-core#12]
Hi!

I've tried adding the GoogleService-Info.plist file to app/assets/iphone but it can't find the file or its invalid(Freshly downloaded from firebase). So i tried passing the file in the configure function as a param, but that just gets me the error "Options is nil". 
I tried it like this: firebaseCore.configure({"file": "GoogleService-Info.plist"});

What am i doing wrong?

Latest xcode and 7.0.2.GA btw.

**Comment by hansemannn** [comment]
Are you using Alloy? If not, it has to be in `/Resources/GoogleService-Info.plist` instead. If you do use Alloy, it should be picked up `from app/assets/iphone`. If that fails, you can manually configure it by passing the properties like `clientID`, `projectID` and `APIKey`. Also, if passing it as a file does not work, it indicates that you have it in the wrong directory. You can check if the plist file is in the actual app-bundle (`build/iphone/build/Products/<your-app>.app/Contents`).

**Comment by michaelkaaring** [comment]
I am using alloy yes. I have the file placed in `app/assets/iphone/GoogleService-Info.plist` but it's not getting picked up as it should. The file is also not added to the actual app-bundle as you previously mentioned. 
I also tried to pass the properties as you suggested but no luck there eather as i get the error `Options is nil`. As i wrote in the original post.

**Comment by michaelkaaring** [comment]
A bit triggerhappy on closing the issue 😏

**Comment by hansemannn** [comment]
This module is used in production by other developers, so your app setup seems to have an issue. If "Options" is nil, it means that Google rejected your configuration in the constructor [here](https://github.com/hansemannn/titanium-firebase-core/blob/master/ios/Classes/FirebaseCoreModule.m#L66).
