### ISSUE TITLE
Configure crashes when sending integer instead of string

### ISSUE THREAD

**Issue by ghost** [hansemannn/titanium-firebase-core#14]
Function `configure()` results in an error when I pass `GCMSenderID` as an integer:

```js
var fcc = require('firebase.core');
        fcc.configure({
            APIKey: 'aaabbbccc',
            projectID: 'proj-id',
            googleAppID: 'a:bbbbasdfcccce',
            GCMSenderID: 2221122211239
        });
```

this is solved by:
```js
GCMSenderID: '2221122211239'
```

I will create a PR for the readme, but a code fix might be handy too.

**Comment by hansemannn** [comment]
The native side requires a String value, so we should be strict and requiring the same. I am welcome accepting a pull request adding the types to the configuration keys!

**Comment by ghost** [comment]
https://github.com/hansemannn/titanium-firebase-core/pull/15
