### ISSUE TITLE
Admob ads not showing on Android wrong firebase version SDK cited

### ISSUE THREAD

**Issue by adamgf** [hansemannn/titanium-firebase-core#20]
Hello I am using appcelerator studio version 7.1.1.GA and am porting an iphone app to android for a client. I tried a bunch of things but am unable to get admob ads to show up in the app and the error message I get is ==>

[WARN] : Ads: Invoke Firebase method getInstance error. [WARN] : Ads: The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date

I am using version 2.2.0 of the 'firebase.core' module, version 4.0.0 of the 'ti.admob' module, version 11.0.40 of ti.playservices (whatever is included with Appcelerator Studio I believe) and version 4.2.0 of the 'ti.map' module. I am also using version 2.0.0 of the ti.googlesignin module. Everything else the map and google signin work fine. I tried a bunch of different things including ti.playservices, not including it and also when I had version 4.1.0 of the 'ti.admob' module installed I was getting dexer linking errors which did not seem right and when I reverted to the 4.0.0 version of 'ti.admob' the linker errors went away.

This is the last thing I need to do to release this app to the Google Play Store I have managed to get everything else is working but it would be a bummer not to have ads in the app. I really don't want to disappoint my client.

**Comment by adamgf** [comment]
I figured out what the issue is.  It is real simple I just had to pass the ad unit id in as the publisher id in Admob.createView({ publisherId: '<use ad unit id not publisher id>', ... });  Talk about confusing it would be nice if that were documented in the ti.admob module readme.  Maybe it is documented somewhere but I did not see anything.

**Comment by kubaizi** [comment]
where did you set publisherId ????
can't find it?
