### ISSUE TITLE
iOS crash on liveview reload

### ISSUE THREAD

**Issue by R4mpancy** [hansemannn/titanium-firebase-core#22]
Liveview makes it very convenient for testing UI changes, however since integrating Firebase into my app successfully I've been unable to use it effectively on iOS because after any reload the app crashes with the error: 
```
[ERROR] Error: Default app has already been configured.
[ERROR] File: app.js
[ERROR] Line: 75
[ERROR] SourceId: <null>
[ERROR] Backtrace:
[ERROR]  undefined
```
I have Looked around for support on the issue and other modules including the Firebase SDK reference a FIRApp.defaultApp property to check if configuration already occurred. This property can be found inside `titanium-firebase-core/ios/platform/FirebaseCore.framework/Headers/FIRApp.h`

```
/**
 * Returns the default app, or nil if the default app does not exist.
 */
+ (nullable FIRApp *)defaultApp NS_SWIFT_NAME(app());
```

When trying to access the FirebaseCore object I just get a null object.
```
var FirebaseCore = require("firebase.core");
Ti.API.debug(FirebaseCore.getOwnPropertyNames()); //[DEBUG] <null>
```

I believe having the defaultApp property exposed and checking if it is set before calling the Core's configure method would alleviate this liveview issue.

**Comment by R4mpancy** [comment]
Submitted a pull request #23 that should fix this

**Comment by hansemannn** [comment]
@R4mpancy Can you please share a new version that I can upload? I am currently not on my Appc macOS, thx!

**Comment by R4mpancy** [comment]
By sharing a new version do you mean, packaging a new version for the releases page?

If so, I'd be more than happy to but I think I need write access to the repo first.

**Comment by R4mpancy** [comment]
Thought that I might be able to create the release on my own forked repo and bundle it into a PR to bring back here, but apparently that's not an option in a PR.
I cannot move forward with drafting a new release until I have Collaborator access.

I'll reopen this ticket in case it being closed has kept notifications silent.

**Comment by hansemannn** [comment]
Released as part of https://github.com/hansemannn/titanium-firebase-core/releases/tag/ios-1.3.0
