### ISSUE TITLE
Default FirebaseApp is not initialized

### ISSUE THREAD

**Issue by AppWerft** [hansemannn/titanium-firebase-core#25]
```
win.addEventListener('open', function() {
	FirebaseCore.configure({
		file:'google-services.json'
	});
});
```

This simple code above generates:

```shell
[ERROR] :  TiBaseActivity: (main) [43,43] Error dispatching lifecycle event: Default FirebaseApp is not initialized in this process de.appwerft.firebauseauth. Make sure to call FirebaseApp.initializeApp(Context) first.
[ERROR] :  TiBaseActivity: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process de.appwerft.firebauseauth. Make sure to call FirebaseApp.initializeApp(Context) first.
[ERROR] :  TiBaseActivity: 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source:60)
[ERROR] :  TiBaseActivity: 	at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:0)
[ERROR] :  TiBaseActivity: 	at firebase.auth.TitaniumFirebaseAuthModule.onStart(TitaniumFirebaseAuthModule.java:94)
[ERROR] :  TiBaseActivity: 	at org.appcelerator.titanium.TiLifecycle.fireLifecycleEvent(TiLifecycle.java:150)
[ERROR] :  TiBaseActivity: 	at org.appcelerator.titanium.TiBaseActivity.onStart(TiBaseActivity.java:1378)
```

**Comment by m1ga** [comment]
But the error is from `TitaniumFirebaseAuthModule`. So where in your code do you use `TitaniumFirebaseAuthModule.onStart`? It looks like this is initialized before win.open()

**Comment by AppWerft** [comment]
This is a very good thought. I will inspect. I have used the original TitaniumFirebaseAuthModule. My new code comes from a submodule. The question is, when the `onStart` will fired? 
I guess:

onAppCreate: if app is started
onStart: if the JS layer calls require

**Comment by hansemannn** [comment]
The app needs to be configured in the `open` event of the root window.

**Comment by AppWerft** [comment]
I guess the root window will build in app.js as first window.
This I did in app.js:

```javascript
var $ = Ti.UI.createWindow();
$.addEventListener('open',function() {
	FirebaseCore.configure();
	FirebaseAuth.createUserWithEmail({
		email:"rainer@com",
		password:"********",
		callback : function(e) {
			FirebaseAuth.signInWithEmail({
				email:"rainer@com",
				password:"********",
				callback : function(e) {
					console.log(e);
				}
			});
		}
	});
});
```
I found in manual:
FirebaseApp.initializeApp() return an instance of FirebaseApp.

In next module `firebase.auth`. in onStart() event in line 76(?) this will call `mAuth = FirebaseAuth.getInstance();`. If I call a Kroll.method like `createUserWithEmail()` `mAuth` is null.

**Comment by AppWerft** [comment]
I found:  `FirebaseCore.configure();` must run *before* window is opened. So the first (splash) activity will taken.
