### ISSUE TITLE
Can't use FirebaseApp  in FirebaseAuth

### ISSUE THREAD

**Issue by AppWerft** [hansemannn/titanium-firebase-core#27]
My goal is to fill the missing methods on Android site ;-)

First I try to test the existent state. This is my test code:

```javascript
const FirebaseCore = require('firebase.core'), FirebaseAuth=require('firebase.auth');
var $ = Ti.UI.createWindow();
$.addEventListener('open',function() {
	FirebaseCore.configure();
	FirebaseAuth.createUserWithEmail({
		email:"rainer@com",
		password:"********",
		callback : function(e) {
			FirebaseAuth.signInWithEmail({
				email:"rainer@com",
				password:"********",
				callback : function(e) {
					console.log(e);
				}
			});
		}
	});
});
```
On logcat I can see, the FirebaseApp will created.  But the call of methods of FirebaseAuth gives me the following error on logcat:

```
[ERROR] :  TiExceptionHandler: (main) [0,65] - Message: Uncaught Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
```

The same issue with all other methods inside Auth. Maybe a stupid thought: FirebaseApp is generated in first core module, how it is visible in second? Perhaps firebase-core returns a FirebaseAppProxy for usage in other modules – or "I'm on the Holzweg"?

Here the full adb logcat:
https://gist.github.com/AppWerft/bb761fcbdb7c6af658c7fecac2a944c1

**Comment by hansemannn** [comment]
This is a general Java question and should be asked on StackOverflow instead.
