### ISSUE TITLE
firebase.core ios 1.3.0 build error

### ISSUE THREAD

**Issue by edwintsai** [hansemannn/titanium-firebase-core#28]
Hi,
When I'm using appcelerator SDK 7.x build ios app, It's error occured.
The android app is working on 7.4.x 

WARN] :   The iOS framework "firebase.core" could not be found. Are you trying to use "FirebaseNanoPB" or "FirebaseInstanceID" or "FirebaseCoreDiagnostics" or "FirebaseCore" or "FirebaseMessaging" instead? (../build/iphone/build/Products/Debug-iphonesimulator/myapp.
app/alloy/controllers/index.js)
[WARN] :   The iOS framework "firebase.cloudmessaging" could not be found. Are you trying to use "FirebaseNanoPB" or "FirebaseInstanceID" or "FirebaseCoreDiagnostics" or "FirebaseCore" or "FirebaseMessaging" instead? (../build/iphone/build/Products/Debug-iphonesimulator/myapp.app/alloy/controllers/index.js)

[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	ProcessPCH /Volumes/DATA2/Appcelerator_Studio_Workspace/tainanshopping2018/build/iphone/build/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/7491688597739658568/myapp_Prefix.pch.gch /Volumes/DATA2/Appcelerator_Studio_Workspace/tainanshopping2018/build/iphone/myapp_Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] :  (1 failure)

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 8589934592
Node.js
  Node.js Version             = 8.9.1
  npm Version                 = 5.5.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = 7.4.1.GA
Support/Titanium/mobilesdk/osx/7.4.1.GA
  Target Platform             = iphone

**Comment by hansemannn** [comment]
Try Core v2.1.0. Also, make sure to use the latest cloud-messaging version.
