### ISSUE TITLE
Problem with GoogleService-Info.plist

### ISSUE THREAD

**Issue by tav3lla** [hansemannn/titanium-firebase-core#3]
Hi,

I have a problem with GoogleService-Info.plist file. 
The errore returned:

[ERROR] :  Error: `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.
[ERROR] :  File: app.js
[ERROR] :  Line: 329
[ERROR] :  SourceId: <null>
[ERROR] :  Backtrace:
[ERROR] :   undefined

where i can insert the "GoogleService-Info.plist" file?
(iOS 11.1, Titatium sdk 6.0.4/6.1.X/6.2.X/6.3.0 GA)

thanks in advance.

**Comment by hansemannn** [comment]
Alloy: `app/assets/iphone/`
Classic: `Resources/`

**Comment by tav3lla** [comment]
Thanks!!!
