### ISSUE TITLE
iOS: Build error

### ISSUE THREAD

**Issue by michielvaneerd** [hansemannn/titanium-firebase-core#31]
Hi,

I'm trying to get cloud messaging to work on iOS, but when I add the firebase-core module for iOS and try to run the app, I receive the following error:

```
[INFO]  Encrypting JavaScript files
[INFO]  Writing i18n files
[INFO]  Processing Titanium symbols
[INFO]  Removing files
[INFO]  Optimizing .plist and .png files
[INFO]  Invoking xcodebuild
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/michielve/Documents/titaniumapps/gs-lemcheck2/build/iphone/build/Intermediates/Lemcheck2.build/Debug-iphoneos/Lemcheck2.build/Objects-normal/armv7/Lemcheck2 normal armv7
[ERROR] (1 failure)
```

I run my app with:

`appc run -p ios -T device`

Module section in tiapp.xml file (this points to the 2.1.0 version of firebase.core module):

```
<modules>
  <module platform="ios">firebase.core</module>
</modules>
```

Other setup information:

```
Operating System
  Name                        = Mac OS X
  Version                     = 10.14.1
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 8.0GB

Node.js
  Node.js Version             = 10.14.1
  npm Version                 = 6.4.1

Appcelerator CLI
  Installer                   = 4.2.13
  Core Package                = 7.0.8

Titanium CLI
  CLI Version                 = 5.1.1
  node-appc Version           = 0.2.44
```

SDK 7.5.0.GA

Does anyone has an idea what could be the issue? Without this module, the app runs okay. On Android everything works okay also with this module.

**Comment by hansemannn** [comment]
Please attach the full trace-log (`appc run -p ios -T device -l trace`), so the actual build error can be seen.

**Comment by michielvaneerd** [comment]
Hi, please see the attached trace log.
[build_iphone.log](https://github.com/hansemannn/titanium-firebase-core/files/2691651/build_iphone.log)

**Comment by hansemannn** [comment]
Oh, StoreKit is missing. Please add `-framework StoreKit` to the module.xcconfig of the module. Patching soon. *EDIT*: Patched. See [here](https://github.com/hansemannn/titanium-firebase-core/blob/master/ios/module.xcconfig) for details. New release (ios-v2.1.1) soon.

**Comment by michielvaneerd** [comment]
Hi Hans, thanks it's working!

**Comment by mediabug51** [comment]
I'm also having similar problem on my iOS simulator:
```
[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/appName.app/appName normal x86_64
[ERROR] :  (1 failure)
```

IOS 11.2 simulator, SDK 7.5.0 GA.

**Comment by hansemannn** [comment]
Please use v2.1.1, thanks.
