### ISSUE TITLE
iOS: The "GTMSessionFetcher" and "GoogleToolboxForMac" frameworks need to be removed when using Ti.GoogleSignIn

### ISSUE THREAD

**Issue by hansemannn** [hansemannn/titanium-firebase-core#34]
When using this module together with [Ti.GoogleSinIn](https://github.com/hansemannn/titanium-google-signin), the above frameworks need to be removed with a small hook, so duplicate symbols can be prevented.

**Comment by fahad86** [comment]
an intermediate fix for anyone looking for one: https://stackoverflow.com/a/41569955/2594721

**Comment by hansemannn** [comment]
This is not an issue anymore, since Google solved this on their peer dependency side
