### ISSUE TITLE
not building together with GoogleSigning Module(iOS) 

### ISSUE THREAD

**Issue by sandeep14** [hansemannn/titanium-firebase-core#35]
Hi,
I have added this two module in My Appcelerator project. But My appcelerator not build with this module.

If I added both module individually then it building properly . but added two module in single project cause me a issue.

[ERROR] : ** BUILD FAILED **

[ERROR] : The following build commands failed:

[ERROR] : Ld /Users/admin/Documents/Appcelerator_Studio_Workspace/testt/build/iphone/build/Products/Debug-iphonesimulator/testt.app/testt normal x86_64

[ERROR] : (1 failure)

Link for both module are
* https://github.com/hansemannn/titanium-google-signin
* https://github.com/hansemannn/titanium-firebase-core
![screenshot 2019-02-11 at 4 38 09 pm](https://user-images.githubusercontent.com/5755440/52563138-8fefc080-2e26-11e9-91a8-39b9131a2897.png)

**Comment by hansemannn** [comment]
This has already been answered on Slack:

> Remove `GTMSessionFetcher.framework` and `GoogleToolboxForMac.framework` from firebase.core. This could be handled with a precompile hook though.
