### ISSUE TITLE
Android - configure error

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-firebase-core#39]
```js
// Firebase lib
/* ===============================
@ Imports
=============================== */
const FirebaseAnalytics = require('firebase.analytics')

/* ===============================
@ Consts & Lets
=============================== */
let Initialized

/* ===============================
@ Functions
=============================== */
Alloy.Firebase = {
	Config: callback => {
		const core = require('firebase.core') // eslint-disable-line
		const configured = core.configure()
		Alloy.Log(`[Firebase - config]: ${JSON.stringify(configured)}`)
		Initialized = true
		callback && callback()
	},
	CloudMessaging: require('firebase.cloudmessaging'), // eslint-disable-line
	Analytics: (event, params) => {
		if (!Alloy.CFG.FIREBASE || !Initialized) return

		// params = params || (OS_IOS ? { action: 'click', category: 'click' } : null)

		Alloy.Log(
			`[Firebase - Analytics]: ${JSON.stringify({
				event,
			})}`,
		)

		FirebaseAnalytics.log(event, {})
	},
}
```

```shell
[ERROR] TiExceptionHandler: (main) [336,336] /core/firebase.js:9
[ERROR] TiExceptionHandler: 		const configured = core.configure();
[ERROR] TiExceptionHandler:                           ^
[ERROR] TiExceptionHandler: Error: ApiKey must be set.
[ERROR] TiExceptionHandler:     at Object.Config (/core/firebase.js:9:27)
[ERROR] TiExceptionHandler:     at Window.openWin (/alloy/controllers/index.js:61:18)
[ERROR] TiExceptionHandler:     at Window.value (ti:/events.js:49:21)
[ERROR] TiExceptionHandler:     at Window.value (ti:/events.js:106:20)
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
[ERROR] TiExceptionHandler:     com.google.firebase.FirebaseOptions$Builder.setApiKey(com.google.firebase:firebase-common@@16.1.0:86)
[ERROR] TiExceptionHandler:     firebase.core.TitaniumFirebaseCoreModule.configure(TitaniumFirebaseCoreModule.java:129)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:979)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1208)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:401)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.proxy.TiWindowProxy.handleMessage(TiWindowProxy.java:127)
[ERROR] TiExceptionHandler:     ti.modules.titanium.ui.WindowProxy.handleMessage(WindowProxy.java:492)
[ERROR] V8Exception: Exception occurred at /core/firebase.js:9: Uncaught Error: ApiKey must be set.
```

I already place my `google-services.json` inside `app/assets/android/`
I'm using:
`ti.playservices 16.1.2`
`firebase.core 4.0.0`
`TiSDK 7.5.1`

**Comment by R4mpancy** [comment]
I was running into this error as well, but upgrading to TiSDK 8.0.0 fixed it.

**Comment by m1ga** [comment]
can you verify that `api_key` is inside the json file with `current_key`

**Comment by DouglasHennrich** [comment]
> I was running into this error as well, but upgrading to TiSDK 8.0.0 fixed it.

I can't update to 8.0.0 right now =/

---

> can you verify that `api_key` is inside the json file with `current_key`

Yea it's there =/

**Comment by m1ga** [comment]
> I was running into this error as well, but upgrading to TiSDK 8.0.0 fixed it.

interesting. Didn't try and older SDK with a newer playservice. Need to check that.

@DouglasHennrich you could try to set the configuration by hand and not using the file. Its a different if-branch 
https://github.com/hansemannn/titanium-firebase-core/blob/ab1ced9073b4b88dfac4907705fcae8595b94b1b/android/src/firebase/core/TitaniumFirebaseCoreModule.java#L73 
so that might work

```
FirebaseCore.configure({
  APIKey: "AIYasZBtfJh..........",
  projectID: "test-12345",
  storageBucket: "test-12345.appspot.com",
  applicationID: "1:12345678890:android:abc123efg456"
});
```

**Comment by R4mpancy** [comment]
@m1ga Yeah for a previous version on 7.5.1 I had to target the older 14_x ti.playservices version and targeting the android firebase-core > 3.0.0 was giving some issues.

**Comment by m1ga** [comment]
the 14.x part was because 8.0 ships with 16 so you had to specify the version otherwise it will use the latest. But I didn't test using the latest module version with an older SDK (so not 8).

**Comment by DouglasHennrich** [comment]
Using
```js
FirebaseCore.configure({
  APIKey: "AIYasZBtfJh..........",
  projectID: "test-12345",
  storageBucket: "test-12345.appspot.com",
  applicationID: "1:12345678890:android:abc123efg456"
});
```

works... but it should work with the file, isn't it ?

**Comment by m1ga** [comment]
yes, I've used the playservice 14.x with a file up to 7.5.1. The `opening file` part didn't change in the new version. Just the firebase aar modules were updated.

**Comment by m1ga** [comment]
Just tried it:
* Ti 7.5.1.GA, 8.0.0.GA
* Core: 4.0.0
* FCM: 2.0.0

with just `fc.configure()` and a file in `app/assets/android/google-services.json`
working fine on a HTC A9 (Android 7).

**Comment by hansemannn** [comment]
See core 5.0.0 and cloud-messaging 2.0.1 for details.

**Comment by roelandp** [comment]
@hansemannn can you elaborate on what you mean with 

> See core 5.0.0 and cloud-messaging 2.0.1 for details.

I'm also facing this api-key error (on android only), and have the google-services json also in place. Would love to keep the project clean. 

Using:
- core 5.0.0 
- FCM 2.0.1

not seeing any specific details in those repo's, or are you saying: "use the example of FCM repo (which uses .configure({config_params_object});" 

Tried building on 8.0.1 GA, 8.0.0 GA

thank you for all the hard work!

**Comment by m1ga** [comment]
please try this method: https://github.com/hansemannn/titanium-firebase#android-notes

**Comment by roelandp** [comment]
I accidentally had the wrong package version for my android app in the tiapp.xml. Changes this to the correct (firebase console corresponding) app.package.name resolved my issue. Thank you again for this module.

**Comment by m1ga** [comment]
@DouglasHennrich had the same error as in your initial question!  #46 should fix that by adding a break in the for-loop which parses the json nodes! In my case there was a `null` added at the end of json which was parsed and that caused some problems. So with this PR you could use the `configure()` only version again

**Comment by DouglasHennrich** [comment]
@m1ga you're awesome 👏

**Comment by m1ga** [comment]
merged
