### ISSUE TITLE
Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector

### ISSUE THREAD

**Issue by ericpolkadoc** [hansemannn/titanium-firebase-core#45]
Environment:
FB Core 5.0 (using firebase-common-16.1.0 && firebase-core-16.0.8)
8.0.0.GA Appc SDK
Titanium 7.0.10
ti.playservices 16.1.3
google-services.json is in app/assets/android

Hi,

Created a new blank project, and when adding core for Android Im getting the Failed resolution for AnalyticsConnector error as seen below.

Any thoughts on what I might be missing?

Thanks!

-- Start application log -----------------------------------------------------
[INFO] :   Project built successfully in 1m 25s 219ms
Address in use, retrying...
Address in use, retrying...
[ERROR] :  Zygote: isWhitelistProcess - Process is Whitelisted
[INFO] :   SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c35,c257,c512,c768, pkgname=com.firebasetest
[ERROR] :  Zygote: accessInfo : 1
[ERROR] :  E/om.firebasetes: Not starting debugger since process cannot load the jdwp agent.
[INFO] :   I/om.firebasetes: The ClassLoaderContext is a special shared library.
[WARN] :   W/om.firebasetes: resources.arsc in APK '/data/app/com.firebasetest-IpVuoimvqlF-BNCzFGozog==/base.apk' is compressed.
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[INFO] :   MultiDex: VM with version 2.1.0 has multidex support
[INFO] :   MultiDex: Installing application
[INFO] :   MultiDex: VM has multidex support, MultiDex support library is disabled.
[INFO] :   FirebaseInitProvider: FirebaseApp initialization unsuccessful
[INFO] :   TiApplication: (main) [813,813] Titanium Javascript runtime: v8
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[INFO] :   firebasetest 1.0 (Powered by Titanium 8.0.0.3726240fa2)
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
Address in use, retrying...
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
Address in use, retrying...
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
Address in use, retrying...
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[WARN] :   2DMatrix: (main) [1570,1570] Ti.UI.2DMatrix DEPRECATED in 8.0.0, in favor of Ti.UI.Matrix2D
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
Address in use, retrying...
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   [LiveView] Error Evaluating app.js @ Line: undefined

[ERROR] :  Error: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
[ERROR] :  File: app.js
[ERROR] :  Line: undefined
[ERROR] :  SourceId: undefined
[ERROR] :  Backtrace:
[ERROR] :  undefined

[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.firebasetest.FirebasetestActivity@ef0cc26
[INFO] :   chatty: uid=10291(com.firebasetest) identical 9 lines
[INFO] :   Adreno: QUALCOMM build                   : d693045, Ia714560336
[INFO] :   Adreno: Build Date                       : 12/04/18
[INFO] :   Adreno: OpenGL ES Shader Compiler Version: EV031.25.03.01
[INFO] :   Adreno: Local Branch                     :
[INFO] :   Adreno: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.3.R1.09.00.00.423.055
[INFO] :   Adreno: Remote Branch                    : NONE
[INFO] :   Adreno: Reconstruct Branch               : NOTHING
[INFO] :   Adreno: Build Config                     : S P 6.0.7 AArch64
[INFO] :   Adreno: PFP: 0x016ee180, ME: 0x00000000
[INFO] :   InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
[INFO] :   ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
[INFO] :   ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
[INFO] :   OpenGLRenderer: Initialized EGL, version 1.4
[INFO] :   APSAnalyticsRunnable: Analytics Started
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   APSAnalyticsRunnable: Analytics service flush complete
[INFO] :   APSAnalyticsRunnable: Stopping Service

**Comment by m1ga** [comment]
you have `analytics` erros so I'm not sure if that is related to the core.
But you have `[INFO] : FirebaseInitProvider: FirebaseApp initialization unsuccessful`. Please use the XML config part from: https://github.com/hansemannn/titanium-firebase#android-notes

**Comment by deckameron** [comment]
@m1ga I am having the same issue, but I haven't downloaded the Firebase.Analytics yet, so it is not in my project. I am still trying to configure the core.
The error occurs just by adding it to the Tiapp.xml and trying this code:

FirebaseCore.configure({
    file : "google-services.json"
});

Environment:
FB Core 5.0
8.0.2.GA Appc SDK

**Comment by m1ga** [comment]
did you follow the install guide (e.g. install ti.playservices) and the XML link from the comment above?

**Comment by deckameron** [comment]
> did you follow the install guide (e.g. install ti.playservices) and the XML link from the comment above?

Yes! I followed it step by step. :)

Maybe I filled some of the information wrong.
Some of the fields does not have the same key name as the google-services.json.
Is "google_app_id" the "mobilesdk_app_id" or the "project_number"?

**Comment by m1ga** [comment]
please add the firebase.cloudmessage module (since I'm using all of them and it works). I think the missing library is inside that module. Don't need to use it, just include it in the tiapp.xml

**Comment by deckameron** [comment]
> please add the firebase.cloudmessage module (since I'm using all of them and it works). I think the missing library is inside that module. Don't need to use it, just include it in the tiapp.xml

It solved the issue!!! 
Thank you @m1ga
