### ISSUE TITLE
Cannot launch iOS app with newer version 3.0.0

### ISSUE THREAD

**Issue by PietroGranati** [hansemannn/titanium-firebase-core#55]
Hi everyone, I were including firebase cloudmessaging in my app including also the core module.
I've already used the combination for push notifications in another app with success, but this time I'm using SDK 9.2.2 with newer version of the modules.
On Android I've fixed all but on iOS i got this error when launching the app and I really cannot figure it out:

`[ERROR] /ti.main.js:14262
[ERROR]   require('./app'); // This event is to be fired after "app.js" execution. Reasons:
[ERROR]           ^
[ERROR] : Couldn't find module: ./app for architecture: arm64
[ERROR]     at require ([native code])
[ERROR]     at Object.<anonymous> (/ti.main.js:14262:10)
[ERROR]     at doLoad (/ti.main.js:14240:15)
[ERROR]     at loadBootstrapScripts (/ti.main.js:14250:11)
[ERROR]     at loadAsync (/ti.main.js:14255:23)
[ERROR]     Foundation 0x000000018b652940 _NSDescriptionWithLocaleFunc + 96
[ERROR]     CoreFoundation 0x000000018a30cfe4 96F8386D-D88A-3C89-A323-A17975C3317F + 778212
[ERROR]     CoreFoundation 0x000000018a30e154 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 160
[ERROR]     TitaniumKit 0x0000000102d475b4 TiLogMessage + 60
[ERROR]     TitaniumKit 0x0000000102d85244 -[TiExceptionHandler reportScriptError:] + 76
[ERROR]     TitaniumKit 0x0000000102d5aac8 -[KrollBridge evalFileOnThread:context:] + 792
[ERROR]     TitaniumKit 0x0000000102d9274c -[KrollInvocation invoke:] + 60
[ERROR]     TitaniumKit 0x0000000102d93194 -[KrollContext invoke:] + 116
[ERROR]     TitaniumKit 0x0000000102d5b998 -[KrollBridge didStartNewContext:] + 2744
[ERROR]     TitaniumKit 0x0000000102d93928 -[KrollContext main] + 1096
[ERROR]     libdispatch.dylib 0x0000000189fa1298 6C143C51-288F-3CD0-84DD-17B9A0AAEE62 + 393880
[ERROR]     libdispatch.dylib 0x0000000189fa2280 6C143C51-288F-3CD0-84DD-17B9A0AAEE62 + 397952
[ERROR]     libdispatch.dylib 0x0000000189f845b0 6C143C51-288F-3CD0-84DD-17B9A0AAEE62 + 275888
[ERROR]     CoreFoundation 0x000000018a2e95d0 96F8386D-D88A-3C89-A323-A17975C3317F + 632272
[ERROR]     CoreFoundation 0x000000018a2e3a78 96F8386D-D88A-3C89-A323-A17975C3317F + 608888
[ERROR]     CoreFoundation 0x000000018a2e2b90 CFRunLoopRunSpecific + 572
[ERROR]     GraphicsServices 0x00000001a0605598 GSEventRunModal + 160
[ERROR]     UIKitCore 0x000000018cbcc638 71B59F62-19DA-3CFF-89E1-DACF333BAB0D + 11716152`

**Comment by hansemannn** [comment]
This does not look like a Firebase issue but something else. We're running v3.0.0 in production since weeks, so it has to be something on your end. Please check!

**Comment by PietroGranati** [comment]
I swear I check before reporting everything, anyway thanks I will figure it out 👍
