### ISSUE TITLE
Firebase core and firebase analytics module are not working in android build

### ISSUE THREAD

**Issue by rasingh2224** [hansemannn/titanium-firebase-core#56]
Hi,

I have installed both firebase core and firebase analytics module in my app. IOS app is working fine but android build is giving following error.

[ERROR] : Failed to run dexer:
[ERROR] :
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Event;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Param;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$UserProperty;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$ConditionalUserProperty;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$Event;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$EventInterceptor;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$OnEventListener;
[ERROR] :
[ERROR] : UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] : java.lang.RuntimeException: Translation has been interrupted
[ERROR] : at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
[ERROR] : at com.android.dx.command.dexer.Main.runMultiDex(Main.java:365)
[ERROR] : at com.android.dx.command.dexer.Main.runDx(Main.java:286)
[ERROR] : at com.android.dx.command.dexer.Main.main(Main.java:244)
[ERROR] : at com.android.dx.command.Main.main(Main.java:95)
[ERROR] : Caused by: java.lang.InterruptedException: Too many errors
[ERROR] : at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
[ERROR] : ... 4 more
[ERROR] Application Installer abnormal process termination. Process exit value was 1

App is using following versions
Titanium sdk: 8.3.1.GA
Firebase core: 3.0.0
Firebase analytics: 2.1.2
ti.playservices : 16.1.3
ti.cloudpush: 5.1.2
ti.admob: 4.3.0
ti.map: 3.1.1

**Comment by m1ga** [comment]
you are using old version of many modules (even for the 8.x branch). Make sure to update them and read e.g. https://github.com/appcelerator-modules/ti.playservices/issues/29#issuecomment-578950662 

also try to update the TI SDK since newer module versions won't support 8.x anymore.

Since that is not an error of the module I'll close this here. If you have any other errors while updating your modules please use tislack

**Comment by rasingh2224** [comment]
Thanks for Responding Michael. I found the issue already and fixed it. 🙂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
