### ISSUE TITLE
Is Inapp-messaging module available?

### ISSUE THREAD

**Issue by karthikTVS** [hansemannn/titanium-firebase-core#58]
Not an issue. Just a clarification. Is Inapp-messaging module available?

**Comment by hansemannn** [comment]
https://github.com/hansemannn/titanium-firebase#features 👍🏼

**Comment by karthikTVS** [comment]
Any separate module to be added for this?

**Comment by hansemannn** [comment]
Yes, please read the repository carefully. It is https://github.com/hansemannn/titanium-firebase-cloud-messaging
