### ISSUE TITLE
iOS: Error when tried to compile

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-firebase-core#6]
I'm getting this error when I try to build my app with Ti.GoogleMaps:
```
[TRACE] ld: warning: directory not found for option '-F/Users/odin/Documents/Projects/Reset/Fleeter/Mobile/Main/build/iphone/../../modules/iphone/ti.googlemaps/1.2.0/platform'
[TRACE] ld: warning: directory not found for option '-F/Users/odin/Library/Application Support/Titanium/modules/iphone/ti.googlemaps/1.2.0/platform'
[TRACE] ld: framework not found FirebaseCore
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld build/Products/Debug-iphonesimulator/Fleeter.app/Fleeter normal x86_64
[ERROR] (1 failure)
```

when I remove the `firebase-core+firebase-analytics` it works just fine and then founds the right version for the `ti.googlemaps` which is 3.10.0.
![captura de tela 2017-11-25 as 19 17 34](https://user-images.githubusercontent.com/10107024/33234903-5978b782-d215-11e7-8c1e-92e578a44c46.png)
![captura de tela 2017-11-25 as 19 19 04](https://user-images.githubusercontent.com/10107024/33234915-893be3ea-d215-11e7-992b-8be3f3f15c3a.png)

I'm using TiSDK 6.3.0.GA

**Comment by hansemannn** [comment]
Can you explain how the google-maps module relates to this issue? Also, please paste the trace-log, which includes the actual compile error.

**Comment by DouglasHennrich** [comment]
I guess it's related because when I remove the firebase, the maps works just fine and gets the right version which is 3.10.0

That is the end of my log with Trace, you need the whole thing?

**Comment by hansemannn** [comment]
yep, the whole log (at least the compile step) would be good.

**Comment by hansemannn** [comment]
Closing for now due to inactivity
