### ISSUE TITLE
Android app crashes on Ti SDK 10.0.0.GA

### ISSUE THREAD

**Issue by riodiep** [hansemannn/titanium-firebase-core#61]
I upgraded my app to Ti SDK 10 and failed to build with below error.

I had the latest module of firebase-core 6.1.1 ; firebase-cloudmessaging 3.1.1 ; ti.playservices 17.5.0

`[ERROR] TiExceptionHandler: (main) [91,91] ti:/kroll.js:1045
[ERROR] TiExceptionHandler:           throw new Error(`Requested module not found: ${request}`); // TODO Set 'code' property to 'MODULE_NOT_FOUND' to match Node?
[ERROR] TiExceptionHandler:        ^
[ERROR] TiExceptionHandler: Error: Requested module not found: ti.playservices\ti.playservices.bootstrap
[ERROR] TiExceptionHandler:     at Module.require (ti:/kroll.js:1045:14)
[ERROR] TiExceptionHandler:     at Module.global.Module.require (<embedded>:5086:32)
[ERROR] TiExceptionHandler:     at require (ti:/kroll.js:1315:22)
[ERROR] TiExceptionHandler:     at global.require (<embedded>:5071:10)
[ERROR] TiExceptionHandler:     at doLoad (<embedded>:11198:27)
[ERROR] TiExceptionHandler:     at loadBootstrapScripts (<embedded>:11224:5)
[ERROR] TiExceptionHandler:     at loadAsync (<embedded>:11229:3)
[ERROR] TiExceptionHandler:     at _startSnapshot (<embedded>:11246:1)
[ERROR] TiExceptionHandler:     at /ti.main.js:1:8
[ERROR] TiExceptionHandler:     at Module._runScript (ti:/kroll.js:1342:24)
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:175)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiApplication.launch(TiApplication.java:868)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiLaunchActivity.loadScript(TiLaunchActivity.java:96)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiRootActivity.loadScript(TiRootActivity.java:497)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiLaunchActivity.onResume(TiLaunchActivity.java:177)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiRootActivity.onResume(TiRootActivity.java:516)
[ERROR] TiExceptionHandler:     android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
[ERROR] TiExceptionHandler:     android.app.Activity.performResume(Activity.java:7962)
[ERROR] TiExceptionHandler:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
[ERROR] V8Exception: Exception occurred at ti:/kroll.js:1045: Uncaught Error: Requested module not found: ti.playservices\ti.playservices.bootstrap`

**Comment by hansemannn** [comment]
This is not a module error. It seems like you forgot to include a required module

**Comment by riodiep** [comment]
Hi @hansemannn 

App crashed and didn't hit alloy.js when I declared the below in my tiapp.xml

`<modules>`
`    <module>firebase.core</module>`
`    <module platform="android">ti.playservices</module>`
`  </modules>`

I tried to comment out one of them, same error occurred. But when I commented out both modules, it went to alloy.js

As you said it might not be an issue with firebase.core module and error mentioned about the ti.playservices. I have tried multiple version of ti.playservices 17+ and all returned the same errors.

Do you think I need to create an issue in ti.playservices instead?

Thank you

Thank you.
