### ISSUE TITLE
9.0.1 failing 

### ISSUE THREAD

**Issue by zenjoe** [hansemannn/titanium-firebase-core#68]
**After switching to Core 9.0.1 it calls this error: (using latest of analytics)**
[ERROR] ti:inspectFrameworks: Duplicate framework FBLPromises detected at these paths:
[ERROR] ti:inspectFrameworks: 
[ERROR] ti:inspectFrameworks:   /Users/joe/Desktop/aaa/xxx/modules/iphone/firebase.analytics/8.0.0/platform/FBLPromises.xcframework
[ERROR] ti:inspectFrameworks:   /Users/joe/Desktop/aaa/xxx/modules/iphone/firebase.core/9.0.1/platform/FBLPromises.xcframework
[ERROR] ti:inspectFrameworks: 
[ERROR] ti:inspectFrameworks: Please resolve this conflict by choosing one of the above frameworks that you want to keep and remove the other before continuing.
Testing on 12.1.2.GA and latest RC 12.2.x

**Comment by hansemannn** [comment]
Can you use Analytics 8.0.1 please? https://github.com/hansemannn/titanium-firebase-analytics/releases/tag/ios-8.0.1

**Comment by zenjoe** [comment]
Yes . confirmed no error when using Analytics 8.0.1 on latest 12.2.x release - Thanks!!

**Comment by hansemannn** [comment]
Cool! :-)
