### ISSUE TITLE
Module does not work with ti.map (v3.3.1, v3.3.0) on Android

### ISSUE THREAD

**Issue by yahya-uddin** [hansemannn/titanium-firebase-core#7]
This module does not seem to work with version 3.3.1 or v3.3.0 of `ti.map` on Android.

I created a new plain app with:

```
    $ appc new
```

In my `tiapp.xml` I have the following modules:

```
<modules>
            <module platform="android" version="3.3.1">ti.map</module>
	    <module platform="android">firebase.core</module>
	    <module platform="commonjs">ti.cloud</module>
</modules>
```

Note that at the time of writing, version 3.3.1 is the latest version of `ti.map`.
I am also using SDK 6.3.0.GA.

I did not modify the sample app in any other way.

When I try to build the app using:

```
$ appc run -p android -T device
```

I get the following error:

```
[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/zza;
[ERROR] 1 error; aborting
```
There does not seem to be any issues with v3.0.1 of `ti.map`.
However, I cannot down-grade as there is quite a few issues with the older version of ti.map.

Please help, as we need FireBase installed on our app as soon as possible!

**Comment by hansemannn** [comment]
When being used together with Ti.Map or other modules that use google-play-services, it requires SDK 7.0.0 and the dedicated versions that use the new `ti.playservices` dependency. If running on 7 Beta, use [Ti.Map 4.0.0](https://github.com/appcelerator-modules/ti.map/releases/tag/android-4.0.0).

**Comment by yahya-uddin** [comment]
How can I add ti.playservices to my application?
Whenever I add ti.playservices to my modules I get the error:

```
[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: ti.playservices   version: latest         platform: android       deploy-type: test
```

Same if I use gittio and cannot be found if I search for it in the IDE

**Comment by hansemannn** [comment]
It's [here](http://gitt.io/component/ti.playservices) ([original repo](https://github.com/appcelerator-modules/ti.playservices)). Please note that you need 7.0.0 for this to work and all other modules need to be recompiled for 7.0.0 as well. The RC release is planned for today, the GA release in 1-2 weeks.

**Comment by yahya-uddin** [comment]
When you say 7.0.0, do you mean 7.0.0 of the Appcelerator Titanium SDK

**Comment by hansemannn** [comment]
That is correct!
