### ISSUE TITLE
IOS Firebase.core configuration issue 

### ISSUE THREAD

**Issue by sibisandaniel86** [hansemannn/titanium-firebase-core#72]
What is the correct whey to configure the core on IOS in the last version, i tried all options , passing a file , passing parameters and im not able to make it work .

**Comment by m1ga** [comment]
check https://github.com/hansemannn/titanium-firebase?tab=readme-ov-file#installation
The easiest/quickest way is to use the config file:
>Download the GoogleService-Info.plist from your project and copy it to [application_name]/Resources/iphone/ (classic) or [application_name]/app/assets/iphone (Alloy)

**Comment by hansemannn** [comment]
Note that if you have a classic app (no Alloy), it's `/Resources/iphone`

**Comment by sibisandaniel86** [comment]
firebase no longer generates a .plist file just a .json , im nut sure if its the same format as the expected .plist.
even so , passing the parameters as:
{
  APIKey: "AIzaSyBCgKuKSB_vseApla_44IO3V7.....",
  projectID: "caza-....",
  storageBucket: "caza-c........",
  applicationID: "1:364396655701:android:........."
}

i get the error : [ERROR] Cannot configure Firebase: Options is nil. Please pass a valid options.

**Comment by m1ga** [comment]
Are you sure about that? I just added a new iOS app and it gives me a plist file. The JSON file is for Android

**Comment by sibisandaniel86** [comment]
sorry , i was trying with the android app , i just generated a new ios app and ... , just me being tired and stupid :).
thanks again .

**Comment by m1ga** [comment]
:+1:  then I'll close this here as it is not an issue with the module
